### ISSUE TITLE
Ability to mark as done all items from Todo list

### ISSUE THREAD

**Issue by brunocerecetto** [toti1212/todo-cli#12]
Hi @toti1212 ! I think it would be great to be able to mark all the tasks as done. 
Yesterday I forgot to update the lists and now I have to mark them one by one 😅

**Comment by toti1212** [comment]
Hi @brunocerecetto! It's a good one 🙂.

A first approach could be passing the `all` _arg_. It would ask you if you want to mark as done all your pending items. It's the faster way and the preferred by me.

Another approach could be made an interactive mode where you can select which items had to be done, but it can be postponed for a version 1.x.x

As you know, PR are welcomed 🎉.

**Comment by brunocerecetto** [comment]
I thought the same thing about the arg.  Tonight or tomorrow I'll throw you the pr 🎉
